"""Criando tabela movimentacao

Revision ID: 69d59e5ed316
Revises: dc3c41527e56
Create Date: 2026-06-01 13:57:52.758505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69d59e5ed316'
down_revision: Union[str, Sequence[str], None] = 'dc3c41527e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('ativa', sa.BOOLEAN(), nullable=True))
    op.alter_column('categorias', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('categorias', 'ativo')
    op.drop_index(op.f('ix_movimentacoes_id'), table_name='movimentacoes')
    op.drop_table('movimentacoes')
    # ### end Alembic commands ###
